### PR TITLE
TP-923: Disable Oshi in surefire tests

### PR DESCRIPTION
**Pull request by ath0s**

### CODE REVIEW

**Review by pativa — APPROVED** [review]
Nice! Do we need to make this change in more branches, or is it enough with the master branch?

**Comment by ath0s** [comment]
> Nice! Do we need to make this change in more branches, or is it enough with the master branch?

I'm thinking the master branch is enough for the time being.

**Review by Bjornelmers — COMMENTED** [review]
For future references it could be a good idea to leave a comment above the property about why we do this. At least it not be obvious at all for me 😅

**Review by Bjornelmers — APPROVED** [review]
Super!

**Pull request merged**
